### ISSUE TITLE
你好，有数据库文件吗，如有可以发我一份吗。2385756401@qq.com

### ISSUE THREAD

**Issue by xxsdnol** [giteecode/petAdoptCommunityPublic#2]

**Comment by giteecode** [comment]
完整源码和数据库收费的，需要请联系微信931708230







                       
原始邮件
                       
                     

发件人："我是秦始皇"< ***@***.*** &gt;;

发件时间：2024/2/22 10:50

收件人："giteecode/petAdoptCommunityPublic"< ***@***.*** &gt;;

抄送人："Subscribed"< ***@***.*** &gt;;

主题：Re: [giteecode/petAdoptCommunityPublic] ***@***.*** (Issue #2)




 
Closed #2 as completed.
